# Maintainer: alphawk <alphawk8@gmail.com>
#
# Local PKGBUILD: builds the Brain.fm desktop wrapper straight from this working
# tree. From the project root run:
#
#     makepkg -si
#
# To publish on the AUR instead, host the source (e.g. a GitHub release tarball
# or a git repo) and replace the `build()`/`package()` `$startdir` references
# with the standard `$srcdir/$pkgname-$pkgver` layout plus a populated
# `source=()`/`sha256sums=()`. See AUR-NOTES in README.md.

pkgname=brain-fm
pkgver=0.1.0
pkgrel=1
pkgdesc="Unofficial Brain.fm desktop wrapper (Tauri) with MPRIS media-key support and tray"
arch=('x86_64')
url="https://www.brain.fm"
license=('MIT')
depends=('webkit2gtk-4.1' 'gtk3' 'libayatana-appindicator' 'hicolor-icon-theme')
makedepends=('cargo' 'pkgconf')
options=('!lto')
source=()
sha256sums=()

build() {
  cd "$startdir/src-tauri"
  export RUSTUP_TOOLCHAIN=stable
  export CARGO_TARGET_DIR="$startdir/src-tauri/target"
  # Keep absolute build paths out of the binary (cleaner, more reproducible).
  export RUSTFLAGS="${RUSTFLAGS:-} --remap-path-prefix=$startdir=/build"
  cargo build --release
}

package() {
  cd "$startdir"

  install -Dm755 "src-tauri/target/release/brain-fm" \
    "$pkgdir/usr/bin/brain-fm"

  install -Dm644 "packaging/brain-fm.desktop" \
    "$pkgdir/usr/share/applications/brain-fm.desktop"

  # Hicolor icons (sizes generated by `tauri icon`).
  install -Dm644 "src-tauri/icons/32x32.png" \
    "$pkgdir/usr/share/icons/hicolor/32x32/apps/brain-fm.png"
  install -Dm644 "src-tauri/icons/128x128.png" \
    "$pkgdir/usr/share/icons/hicolor/128x128/apps/brain-fm.png"
  install -Dm644 "src-tauri/icons/128x128@2x.png" \
    "$pkgdir/usr/share/icons/hicolor/256x256/apps/brain-fm.png"
  install -Dm644 "src-tauri/icons/icon.png" \
    "$pkgdir/usr/share/icons/hicolor/512x512/apps/brain-fm.png"
}
